// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: task_register.proto

package task_register

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RegistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowID string                      `protobuf:"bytes,1,opt,name=workflowID,proto3" json:"workflowID,omitempty"`
	NodeState  []*RegistRequest_NodesState `protobuf:"bytes,2,rep,name=nodeState,proto3" json:"nodeState,omitempty"`
}

func (x *RegistRequest) Reset() {
	*x = RegistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_register_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRequest) ProtoMessage() {}

func (x *RegistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_register_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRequest.ProtoReflect.Descriptor instead.
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return file_task_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegistRequest) GetWorkflowID() string {
	if x != nil {
		return x.WorkflowID
	}
	return ""
}

func (x *RegistRequest) GetNodeState() []*RegistRequest_NodesState {
	if x != nil {
		return x.NodeState
	}
	return nil
}

type RegistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept uint32 `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *RegistReply) Reset() {
	*x = RegistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_register_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistReply) ProtoMessage() {}

func (x *RegistReply) ProtoReflect() protoreflect.Message {
	mi := &file_task_register_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistReply.ProtoReflect.Descriptor instead.
func (*RegistReply) Descriptor() ([]byte, []int) {
	return file_task_register_proto_rawDescGZIP(), []int{1}
}

func (x *RegistReply) GetAccept() uint32 {
	if x != nil {
		return x.Accept
	}
	return 0
}

type RegistRequest_NodesState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"` //string taskState = 2;//no in register request
}

func (x *RegistRequest_NodesState) Reset() {
	*x = RegistRequest_NodesState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_register_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistRequest_NodesState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRequest_NodesState) ProtoMessage() {}

func (x *RegistRequest_NodesState) ProtoReflect() protoreflect.Message {
	mi := &file_task_register_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRequest_NodesState.ProtoReflect.Descriptor instead.
func (*RegistRequest_NodesState) Descriptor() ([]byte, []int) {
	return file_task_register_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegistRequest_NodesState) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

var File_task_register_proto protoreflect.FileDescriptor

var file_task_register_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x49, 0x44, 0x12, 0x45, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x24, 0x0a,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x32, 0x58, 0x0a, 0x0c, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0a, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x72, 0x0a, 0x1e, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_register_proto_rawDescOnce sync.Once
	file_task_register_proto_rawDescData = file_task_register_proto_rawDesc
)

func file_task_register_proto_rawDescGZIP() []byte {
	file_task_register_proto_rawDescOnce.Do(func() {
		file_task_register_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_register_proto_rawDescData)
	})
	return file_task_register_proto_rawDescData
}

var file_task_register_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_task_register_proto_goTypes = []interface{}{
	(*RegistRequest)(nil),            // 0: task_register.RegistRequest
	(*RegistReply)(nil),              // 1: task_register.RegistReply
	(*RegistRequest_NodesState)(nil), // 2: task_register.RegistRequest.NodesState
}
var file_task_register_proto_depIdxs = []int32{
	2, // 0: task_register.RegistRequest.nodeState:type_name -> task_register.RegistRequest.NodesState
	0, // 1: task_register.TaskRegister.TaskRegist:input_type -> task_register.RegistRequest
	1, // 2: task_register.TaskRegister.TaskRegist:output_type -> task_register.RegistReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_register_proto_init() }
func file_task_register_proto_init() {
	if File_task_register_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_register_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_register_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_register_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistRequest_NodesState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_register_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_register_proto_goTypes,
		DependencyIndexes: file_task_register_proto_depIdxs,
		MessageInfos:      file_task_register_proto_msgTypes,
	}.Build()
	File_task_register_proto = out.File
	file_task_register_proto_rawDesc = nil
	file_task_register_proto_goTypes = nil
	file_task_register_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TaskRegisterClient is the client API for TaskRegister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskRegisterClient interface {
	// Sends a register request
	TaskRegist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistReply, error)
}

type taskRegisterClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskRegisterClient(cc grpc.ClientConnInterface) TaskRegisterClient {
	return &taskRegisterClient{cc}
}

func (c *taskRegisterClient) TaskRegist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistReply, error) {
	out := new(RegistReply)
	err := c.cc.Invoke(ctx, "/task_register.TaskRegister/TaskRegist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskRegisterServer is the server API for TaskRegister service.
type TaskRegisterServer interface {
	// Sends a register request
	TaskRegist(context.Context, *RegistRequest) (*RegistReply, error)
}

// UnimplementedTaskRegisterServer can be embedded to have forward compatible implementations.
type UnimplementedTaskRegisterServer struct {
}

func (*UnimplementedTaskRegisterServer) TaskRegist(context.Context, *RegistRequest) (*RegistReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskRegist not implemented")
}

func RegisterTaskRegisterServer(s *grpc.Server, srv TaskRegisterServer) {
	s.RegisterService(&_TaskRegister_serviceDesc, srv)
}

func _TaskRegister_TaskRegist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRegisterServer).TaskRegist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task_register.TaskRegister/TaskRegist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRegisterServer).TaskRegist(ctx, req.(*RegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskRegister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task_register.TaskRegister",
	HandlerType: (*TaskRegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskRegist",
			Handler:    _TaskRegister_TaskRegist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_register.proto",
}
